_BASE_: "Ssdd-DiffSARShipInst_ResNet50.yaml"
MODEL:
  WEIGHTS: "./model/DiffSARShipInst_res50.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffSARShipInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (3500, 4200) #(87500, 105000) #(350000, 420000)
  MAX_ITER: 4500 #112500 #450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
